env:
    FIRMWARE_DIR: fw

name: reviung34

on:
    push:
        branches:
            - master
            - dcai
        paths:
            - "**reviung34**"
    workflow_dispatch:

jobs:
    build-vial:
        runs-on: ubuntu-latest
        container: qmkfm/qmk_cli

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 1
                  persist-credentials: false

            - name: qmk setup
              run: |
                  git config --global safe.directory "*"
                  python3 -m pip install -r ./requirements.txt
                  qmk setup -y

            - name: build fimrware
              run: |
                  qmk compile -kb reviung/reviung34 -km vial -e CONVERT_TO=promicro_rp2040
                  mkdir ${{ env.FIRMWARE_DIR }}
                  find .build/ -regex '.*\.\(hex\|uf2\)$' -exec cp {} ./${{ env.FIRMWARE_DIR }} \;
                  ls -l ./${{ env.FIRMWARE_DIR }}

            - name: publish firmware
              uses: actions/upload-artifact@v3
              with:
                  name: vial_reviung34-${{ github.run_number }}
                  path: ${{ env.FIRMWARE_DIR }}
